--Funcion para mostrar el listado de tickets

declare
v_sql varchar2(4000);
begin

   if :P23_TIPOUSUARIO = 3 then
	v_sql := '
	select T.COD_TICKET,
	G.DESCRIPCION AS GESTION,
	E.DESCRIPCION AS ESTADO,
	(SELECT NOMBRE FROM CMS_USUARIOS USE WHERE T.COD_USUARIO_SOLICITA = USE.NOM_USUARIO) AS "SOLICITANTE",
	(SELECT NOMBRE FROM CMS_USUARIOS USU WHERE T.COD_USUARIO_GESTOR = USU.COD_USUARIO) AS "GESTOR DEL PROCESO",
	T.TITULO,
	T.DESCRIPCION,
	P.DESCRIPCION AS PRIORIDAD,
	U.DESCRIPCION AS UBICACION,
	D.DESCRIPCION AS DEPARTAMENTO,
	S.DESCRIPCION AS SERVICIO,
	sys.dbms_lob.getlength(T.ADJUNTO)"ADJUNTO",
	T.SOLUCION,
	T.FEC_CREACION
	from CMS_DETA_TICKETS T
	LEFT JOIN CMS_TIPO_GESTION G ON T.COD_TIPO_GESTION = G.COD_TIPO_GESTION
	LEFT JOIN CMS_PRIORIDADES P ON T.COD_PRIORIDAD = P.COD_PRIORIDAD
	LEFT JOIN CMS_UBICACIONES U ON T.COD_UBICACION = U.COD_UBICACION
	LEFT JOIN CMS_DEPARTAMENTOS D ON T.COD_DEPTO = D.COD_DEPARTAMENTO
	LEFT JOIN CMS_DETALLE_SERVICIOS S ON T.COD_SERVICIO = S.COD_DETALLE_SERVICIO
	LEFT JOIN CMS_ESTADOS E ON T.COD_ESTADO = E.COD_ESTADO
	where cod_usuario_solicita =:APP_USER
	ORDER BY T.COD_TICKET ASC';
   else
    v_sql := '
	select T.COD_TICKET,
	G.DESCRIPCION AS GESTION,
	E.DESCRIPCION AS ESTADO,
	(SELECT NOMBRE FROM CMS_USUARIOS USE WHERE T.COD_USUARIO_SOLICITA = USE.NOM_USUARIO) AS "SOLICITANTE",
	(SELECT NOMBRE FROM CMS_USUARIOS USU WHERE T.COD_USUARIO_GESTOR = USU.COD_USUARIO) AS "GESTOR DEL PROCESO",
	T.TITULO,
	T.DESCRIPCION,
	P.DESCRIPCION AS PRIORIDAD,
	U.DESCRIPCION AS UBICACION,
	D.DESCRIPCION AS DEPARTAMENTO,
	S.DESCRIPCION AS SERVICIO,
	sys.dbms_lob.getlength(T.ADJUNTO)"ADJUNTO",
	T.SOLUCION,
	T.FEC_CREACION
	from CMS_DETA_TICKETS T
	LEFT JOIN CMS_TIPO_GESTION G ON T.COD_TIPO_GESTION = G.COD_TIPO_GESTION
	LEFT JOIN CMS_PRIORIDADES P ON T.COD_PRIORIDAD = P.COD_PRIORIDAD
	LEFT JOIN CMS_UBICACIONES U ON T.COD_UBICACION = U.COD_UBICACION
	LEFT JOIN CMS_DEPARTAMENTOS D ON T.COD_DEPTO = D.COD_DEPARTAMENTO
	LEFT JOIN CMS_DETALLE_SERVICIOS S ON T.COD_SERVICIO = S.COD_DETALLE_SERVICIO
	LEFT JOIN CMS_ESTADOS E ON T.COD_ESTADO = E.COD_ESTADO
	where cod_depto =:P23_DEPTO
	ORDER BY T.COD_TICKET ASC';
   end if;
   
   RETURN v_sql;
end;