create or replace PROCEDURE CREAR_USUARIO(
	V_NOM_USUARIO VARCHAR2,
	V_CLAVE VARCHAR2,
	V_NOMBRE VARCHAR2,
	V_CORREO VARCHAR2,
	V_EXTENSION NUMBER,
	V_ESTADO VARCHAR2,
	V_COD_DEPARTAMENTO NUMBER,
	V_COD_TIPO_USUARIO NUMBER
)
AS
BEGIN
 INSERT INTO CMS_USUARIOS
   (
	NOM_USUARIO,
	CLAVE,
	NOMBRE,
	CORREO,
	EXTENSION,
	ESTADO,
	COD_DEPARTAMENTO,
	COD_TIPO_USUARIO)
   VALUES
   (
    V_NOM_USUARIO,
	V_CLAVE,
	V_NOMBRE,
	V_CORREO,
	V_EXTENSION,
	V_ESTADO,
	V_COD_DEPARTAMENTO,
	V_COD_TIPO_USUARIO
	);

END;


