create or replace PROCEDURE CREAR_TICKET(
	V_COD_GESTION VARCHAR2,
	V_COD_ESTADO NUMBER,
	V_COD_PRIORIDAD NUMBER,
	V_COD_USUARIO_SOLICITA VARCHAR2,
	V_COD_USUARIO_GESTOR VARCHAR2,
	V_COD_USUARIO_MODIFICA VARCHAR2,
	V_COD_UBICACION NUMBER,
	V_COD_DEPTO NUMBER,
	V_COD_DETALLE_SERVICIO NUMBER,
	V_TITULO VARCHAR2,
	V_DESCRIPCION VARCHAR2,
	V_SOLUCION VARCHAR2,
	V_FEC_CREACION DATE
)
AS
BEGIN
 INSERT INTO CMS_TICKETS_DETA
   (
    COD_TIPO_GESTION,
    COD_ESTADO,
    COD_PRIORIDAD,
	COD_USUARIO_SOLICITA,
    COD_USUARIO_GESTOR,
    COD_USUARIO_MODIFICA,
    TITULO,
    DESCRIPCION,
    SOLUCION,
    COD_UBICACION,
    COD_DEPARTAMENTO,
    COD_DETALLE_SERVICIO,
    FEC_CREACION)
   VALUES
   (
     V_COD_GESTION,
      V_COD_ESTADO,
	V_COD_PRIORIDAD,
	V_COD_USUARIO_SOLICITA,
	V_COD_USUARIO_GESTOR,
	V_COD_USUARIO_MODIFICA,
	V_TITULO,
	V_DESCRIPCION,
	V_SOLUCION,
	V_COD_UBICACION,
	V_COD_DEPTO,
	V_COD_DETALLE_SERVICIO,
	V_FEC_CREACION);

	COMMIT;

END;
